"""add resume is_primary flag

Revision ID: 14cac5fce49b
Revises: fd8b72ec8fcc
Create Date: 2026-08-20 12:03:50.331238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14cac5fce49b'
down_revision: Union[str, Sequence[str], None] = 'fd8b72ec8fcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('is_primary', sa.Boolean(), nullable=False, server_default=sa.false())
        )

    # Every profile that already has resumes needs exactly one primary, or the
    # unique index below (and the app's "there is always a primary" invariant)
    # would be violated on first read. Pick the earliest-created resume per
    # profile -- the same tie-break create_resume() uses for a brand-new
    # profile's first upload.
    op.execute(
        """
        UPDATE resume
        SET is_primary = 1
        WHERE id IN (
            SELECT id FROM resume AS r
            WHERE r.id = (
                SELECT MIN(id) FROM resume WHERE profile_id = r.profile_id
            )
        )
        """
    )

    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.create_index('uq_resume_primary_per_profile', ['profile_id'], unique=True, sqlite_where=sa.text('is_primary'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume', schema=None) as batch_op:
        batch_op.drop_index('uq_resume_primary_per_profile', sqlite_where=sa.text('is_primary'))
        batch_op.drop_column('is_primary')

    # ### end Alembic commands ###
