"""add preferences notification threshold

Revision ID: 6be0f711f0f3
Revises: 1ca39ea10a65
Create Date: 2026-08-20 20:17:29.810007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6be0f711f0f3'
down_revision: Union[str, Sequence[str], None] = '1ca39ea10a65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notification_threshold', sa.Float(), server_default=sa.text('(0.6)'), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('preferences', schema=None) as batch_op:
        batch_op.drop_column('notification_threshold')

    # ### end Alembic commands ###
