"""initial schema

Revision ID: b289cf842757
Revises: 
Create Date: 2026-08-19 17:47:12.871209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b289cf842757'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('manual', 'indeed', 'linkedin', 'naukri', 'ats_feed', name='sourcekind', native_enum=False, length=32), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('work_mode', sa.Enum('remote', 'hybrid', 'onsite', 'any', name='workmode', native_enum=False, length=32), nullable=False),
    sa.Column('job_type', sa.Enum('full_time', 'internship', 'contract', 'part_time', 'unknown', name='jobtype', native_enum=False, length=32), nullable=False),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=True),
    sa.Column('experience_min_years', sa.Float(), nullable=True),
    sa.Column('experience_max_years', sa.Float(), nullable=True),
    sa.Column('bond_months', sa.Integer(), nullable=True),
    sa.Column('contract_months', sa.Integer(), nullable=True),
    sa.Column('education_requirements', sa.JSON(), nullable=False),
    sa.Column('required_skill_ids', sa.JSON(), nullable=False),
    sa.Column('preferred_skill_ids', sa.JSON(), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('filtered_out_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job')),
    sa.UniqueConstraint('source', 'source_ref', name='uq_job_source_ref')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index('ix_job_company_designation', ['company', 'designation'], unique=False)

    op.create_table('placement_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gmail_message_id', sa.String(length=128), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('shortlisted', 'rejected', 'pending', 'unknown', name='placementstatus', native_enum=False, length=32), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('matched_on', sa.JSON(), nullable=False),
    sa.Column('source_document', sa.Text(), nullable=True),
    sa.Column('raw_row', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_record'))
    )
    with op.batch_alter_table('placement_record', schema=None) as batch_op:
        batch_op.create_index('ix_placement_record_message', ['gmail_message_id'], unique=False)

    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('college', sa.String(length=200), nullable=True),
    sa.Column('department', sa.String(length=200), nullable=True),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('name_aliases', sa.JSON(), nullable=False),
    sa.Column('onboarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_profile'))
    )
    op.create_table('job_requirement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('required_skill', 'preferred_skill', 'responsibility', 'qualification', 'role_title', name='requirementkind', native_enum=False, length=32), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('skill_ids', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=96), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_job_requirement_job_id_job'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_requirement'))
    )
    with op.batch_alter_table('job_requirement', schema=None) as batch_op:
        batch_op.create_index('ix_job_requirement_job_kind', ['job_id', 'kind'], unique=False)

    op.create_table('placement_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=False),
    sa.Column('event_type', sa.Enum('interview', 'technical_round', 'hr_round', 'coding_test', 'assessment', 'pre_placement_talk', 'other', name='eventtype', native_enum=False, length=32), nullable=False),
    sa.Column('round_name', sa.String(length=120), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.String(length=16), nullable=True),
    sa.Column('end_time', sa.String(length=16), nullable=True),
    sa.Column('reporting_time', sa.String(length=16), nullable=True),
    sa.Column('venue', sa.Text(), nullable=True),
    sa.Column('meeting_link', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.Column('calendar_event_id', sa.String(length=255), nullable=True),
    sa.Column('extraction_confidence', sa.Float(), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['record_id'], ['placement_record.id'], name=op.f('fk_placement_event_record_id_placement_record'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_placement_event')),
    sa.UniqueConstraint('dedupe_key', name='uq_placement_event_dedupe')
    )
    op.create_table('preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('target_roles', sa.JSON(), nullable=False),
    sa.Column('preferred_industries', sa.JSON(), nullable=False),
    sa.Column('preferred_locations', sa.JSON(), nullable=False),
    sa.Column('work_mode', sa.Enum('remote', 'hybrid', 'onsite', 'any', name='workmode', native_enum=False, length=32), nullable=False),
    sa.Column('min_salary', sa.Float(), nullable=True),
    sa.Column('preferred_salary_min', sa.Float(), nullable=True),
    sa.Column('preferred_salary_max', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('willing_to_relocate', sa.Boolean(), nullable=False),
    sa.Column('target_experience_years', sa.Float(), nullable=True),
    sa.Column('accepts_fixed_term', sa.Boolean(), nullable=False),
    sa.Column('max_contract_months', sa.Integer(), nullable=True),
    sa.Column('accepts_service_bond', sa.Boolean(), nullable=False),
    sa.Column('max_bond_months', sa.Integer(), nullable=True),
    sa.Column('other_restrictions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_preferences_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preferences'))
    )
    op.create_table('resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('target_role', sa.String(length=160), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('job_category', sa.String(length=120), nullable=True),
    sa.Column('source_format', sa.String(length=16), nullable=False),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], name=op.f('fk_resume_profile_id_profile'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume')),
    sa.UniqueConstraint('profile_id', 'label', 'version', name=op.f('uq_resume_profile_id_label_version'))
    )
    op.create_table('match_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('semantic_score', sa.Float(), nullable=False),
    sa.Column('personalized_score', sa.Float(), nullable=False),
    sa.Column('explanation', sa.JSON(), nullable=False),
    sa.Column('scoring_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_match_result_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], name=op.f('fk_match_result_resume_id_resume'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_match_result')),
    sa.UniqueConstraint('job_id', 'resume_id', name='uq_match_job_resume')
    )
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.create_index('ix_match_personalized_score', ['personalized_score'], unique=False)

    op.create_table('resume_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('skill', 'project_bullet', 'experience_bullet', 'education', 'certification', 'achievement', 'summary', name='chunkkind', native_enum=False, length=32), nullable=False),
    sa.Column('section', sa.String(length=120), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('skill_ids', sa.JSON(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=96), nullable=True),
    sa.Column('embedding_dim', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], name=op.f('fk_resume_chunk_resume_id_resume'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_resume_chunk'))
    )
    with op.batch_alter_table('resume_chunk', schema=None) as batch_op:
        batch_op.create_index('ix_resume_chunk_resume_kind', ['resume_id', 'kind'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resume_chunk', schema=None) as batch_op:
        batch_op.drop_index('ix_resume_chunk_resume_kind')

    op.drop_table('resume_chunk')
    with op.batch_alter_table('match_result', schema=None) as batch_op:
        batch_op.drop_index('ix_match_personalized_score')

    op.drop_table('match_result')
    op.drop_table('resume')
    op.drop_table('preferences')
    op.drop_table('placement_event')
    with op.batch_alter_table('job_requirement', schema=None) as batch_op:
        batch_op.drop_index('ix_job_requirement_job_kind')

    op.drop_table('job_requirement')
    op.drop_table('profile')
    with op.batch_alter_table('placement_record', schema=None) as batch_op:
        batch_op.drop_index('ix_placement_record_message')

    op.drop_table('placement_record')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_company_designation')

    op.drop_table('job')
    # ### end Alembic commands ###
