"""add tailored_resume table

Revision ID: c95394d26433
Revises: 6be0f711f0f3
Create Date: 2026-08-21 09:35:10.253021

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c95394d26433'
down_revision: Union[str, Sequence[str], None] = '6be0f711f0f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailored_resume',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tex', sa.Text(), nullable=False),
    sa.Column('change_log', sa.JSON(), nullable=False),
    sa.Column('excluded_bullet_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_tailored_resume_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], name=op.f('fk_tailored_resume_resume_id_resume'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tailored_resume')),
    sa.UniqueConstraint('resume_id', 'job_id', name='uq_tailored_resume_resume_job')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tailored_resume')
    # ### end Alembic commands ###
