"""add outreach_draft table

Revision ID: e05381b7b5c7
Revises: e5234ad4fa59
Create Date: 2026-08-23 14:31:06.409040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e05381b7b5c7'
down_revision: Union[str, Sequence[str], None] = 'e5234ad4fa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('outreach_draft',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('fk_outreach_draft_job_id_job'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resume.id'], name=op.f('fk_outreach_draft_resume_id_resume'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outreach_draft')),
    sa.UniqueConstraint('resume_id', 'job_id', name='uq_outreach_draft_resume_job')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('outreach_draft')
    # ### end Alembic commands ###
